### ISSUE TITLE
Catquiz feedback settings - potential issues / improvements

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-local_catquiz#306] opened 2024-02-03 08:42 UTC
- [x] 1. Range limits. 

Tested chanhes seems not saved, calculated values enforced
Example for 2 range scales:
-on catquiz editing ranges changed to
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/6528efc3-896a-4bad-837a-12d3b6f11cce)
- after saving it reverts back to pre-calculated values
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/546b9eca-8702-4c64-aba4-0f16e527b41c)

- [x] 1.1 Are the conditions available when user can change those limits?

- [x] 1.2 If not - I would suggest to replace input elements with staic HTML to not to distract user...

- [ ] 2. Wb_colorpicker

- [ ] 2.1 Visibility of value

- on editing after colorrange being selected - a data-value has been shown next to it
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/302b0947-6fe1-496a-a3aa-9c7a14085189)
- after saving - that value not displayed. Or should it to be displayed at all?
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/67d86b11-f3f3-4aec-ab60-24431505df76)
- [x] finally - selected color barely visible (black circle looks not enough?)

- [x] 2.2 HTML attributes

After saving - internal "select" HTML element has another "selected" item than it defined (and visible) via UI
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/322f4374-ec3f-4460-b604-a57dac1c286e)
Is it correct?

- [ ] 3. Regarding Behat test of catquiz settings.

Scenario: "CATquiz settings: teacher setup basic feedback settings" at the moment contains lots of extra steps:
a) to test above issue 1.
b) to compare accessing feedback section in 2 ways 
- or by using of custom "div" ("wraps" each "range" section, A.Semenets proposed) 
- or by using custom behat step (G.Maisser created).
Should we choose only single way? Especially - should custom "div" that "wraps" each "range" section has to be removed?
In fact, to setup values - custom behat step looks slightly better - in case of wb_colorpicker especially.
c) related to previous. Values of recurent "feedback" fields could be accessed directly via xpath which, in fact , very complex  (loook at the [end of commit ](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/commit/bd40961462c08caa2f2a88b5fcbaca46b4e4d35c). It is possible to try to create custom behat step to "get" values of those fields in the similar way they were "set"... But not sure if it worth of time (because of possiblilty of direct access) Opinions on this?

- [ ] 4. Feedback validation not visible until feedback expanded.

It is necessary to expand all (or only necessary) feedback setting section(s) in case if validation errors occurs:
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/96707440-05d3-4a24-bc31-b5026023d9e6)
Because currently all feedback sections are collapsed and no errors visible.

**Comment by eynimeni** [comment] 2024-02-13 10:12
ad 1)
the problem with the lost values should be fixed in GH-283 
also first and last value is fixed. 

Could you @semteacher please add a validation to these forms? Min of range 2 should be exactly Max of range of range 1 etc. 
I already prepared a string (german and english): 'nogapallowed'
If this is complicated because labels change dynamically, let me know I can provide help!

**Comment by eynimeni** [comment] 2024-02-13 13:14
ad 2) I could not really reproduce the error, but I tried to fix it anyway. Can you please recheck?

**Closed** 2024-06-27 10:23 UTC
Labels: bug, enhancement, question
