### ISSUE TITLE
"Edit item param" form on the "Questions" tab do nothing

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-local_catquiz#383] opened 2024-03-16 14:49 UTC
"Edit item param" form on the "Questions" tab do nothing:
- does not displaying current values,
- enterd changes does not applied.
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/fffc750b-85ac-4fbf-8cda-43d164e049da)

**Comment by eynimeni** [comment] 2024-03-18 10:45
duplicate of #166

**Closed by eynimeni** 2024-03-18 10:45 UTC
